---
#########################################
### MOSARTWMPY Configuration Defaults ###
#########################################
### READ ONLY
### To override configuration defaults, edit config.yaml

###
### Simulation
###
simulation:
    # name this simulation
    name: mosartwmpy
    # date to begin the simulation
    start_date: 1981-01-01
    # date to end the simulation
    end_date: 1981-01-31
    # mosart timestep in seconds
    timestep: 10800
    # subcycles - subtimestep will be timestep / subcycles
    subcycles: 3
    # routing iterations - subsubtimestep will be timestep / subcycles / routing_iterations - then further subdivided within subnetwork and main channel based on convergence estimations
    routing_iterations: 5
    # log level, one of DEBUG, INFO, WARNING, ERROR, CRITICAL
    log_level: INFO
    # whether or not to log to console; slightly more efficient to disable this when running on a cluster
    log_to_std_out: true
    # whether or not to log to file; slightly more efficient to disable, but useful for keeping a record of experiment
    log_to_file: true
    # resume simulation from restart file
    restart_file: ~
    # how often to write a restart file; one of 'daily', 'monthly', 'yearly' -- a restart file is also always written at the end of the simulation
    restart_file_frequency: yearly
    # path to a directory for writing output files; will be created if doesn't exist
    output_path: ./output
    # output write frequency in simulation seconds; must be a multiple of simulation timestep; values will be averaged across the intervening timesteps
    # TODO only daily (86400) is currently supported
    output_resolution: 86400 # output values once each day, averaged across the timesteps
    # how often to write a new output file; one of 'daily', 'monthly', 'yearly'
    output_file_frequency: monthly
    # time dependent output fields
    output:
        - variable: hillslope_surface_runoff
          name: QSUR_LIQ
          long_name: Surface runoff
          units: m/s
        - variable: hillslope_subsurface_runoff
          name: QSUB_LIQ
          long_name: Subsurface runoff
          units: m/s
        - variable: storage
          name: STORAGE_LIQ
          long_name: Mosart liquid storage
          units: m3
        - variable: runoff_land
          name: RIVER_DISCHARGE_OVER_LAND_LIQ
          long_name: Mosart river basin flow (same as channel_outflow)
          units: m3/s
        - variable: channel_inflow_upstream
          name: channel_inflow
          long_name: Mosart main channel inflow to grid cell
          units: m3/s
        - variable: runoff_land
          name: channel_outflow
          long_name: Mosart main channel outflow from grid cell
          units: m3/s
        - variable: reservoir_storage
          name: WRM_STORAGE
          long_name: Mosart storage in reservoir
          units: m3
        - variable: grid_cell_supply
          name: WRM_SUPPLY
          long_name: Mosart reservoir supply to grid cell
          units: m3/s
        - variable: grid_cell_demand_rate
          name: WRM_DEMAND
          long_name: Mosart demand reqeusted by grid cell
          units: m3/s
        - variable: grid_cell_deficit
          name: WRM_DEFICIT
          long_name: Mosart unmet demand at grid cell
          units: m3
    # non time dependent fields to include in the output
    # note that latitude and longitude are automatically included as 'lat' and 'lon'
    grid_output:
        - variable: id
          name: GINDEX
          long_name: Index of the grid cell in a 1d array
        - variable: nldas_id
          name: NLDAS_ID
          long_name: NLDAS_ID of grid cell. 
        - variable: outlet_id
          name: OUTLETG
          long_name: Index of the outlet grid cell in a 1d array
        - variable: downstream_id
          name: DSIG
          long_name: Index of the downstream grid cell in a 1d array
        - variable: land_mask
          name: MASK
          long_name: Land mask 1=Land, 2=Ocean, 3=Outlet
        - variable: area
          name: area
          long_name: area
        - variable: total_drainage_area_multi
          name: areatotal
          long_name: areatotal
        - variable: total_drainage_area_single
          name: areatotal2
          long_name: areatotal2

### 
### Grid
###
grid:
    # path to the grid domain file; can be absolute or relative to the source code root
    path: ./input/domains/mosart_conus_nldas_grid.nc
    # longitude field name
    longitude: lon
    # latitude field name
    latitude: lat
    # limit simulation to particular basins
    #   ~ for all, or
    #   a list of coordinate pairs to simulate only basins that include them, i.e:
    #     subdomain:
    #       - 47.6062,-122.3321
    #       - 45.5152,-122.6784
    subdomain: ~
    # Specify whether to unmask the output
    #   - true if output should cover the whole domain regardless of active cells (inactive cells will be filled with NaN-like values)
    #   - false if output should only consist of active cells
    # False will result in faster runs and much smaller output sizes, but the output may be more difficult to interoperate with other models
    unmask_output: true
    # variable field names
    variables:
        # fraction of unit draining to outlet field
        drainage_fraction: frac
        # local drainage area field name
        local_drainage_area: area
        # total upstream drainage area using concept of multi flow direction field name [m2]
        total_drainage_area_multi: areaTotal
        # total upstream drainage area using concept of single flow direction field name [m2]
        total_drainage_area_single: areaTotal2
        # grid cell id field name
        id: ID
        # NLDAS_Id of the grid cell
        nldas_id: NLDAS_ID
        # downstream ID field name
        downstream_id: dnID
        # flow direction field name
        flow_direction: fdir
        # Manning roughness coefficient for overland flow field name
        hillslope_manning: nh
        # Manning's roughness coefficient for tributary channel flow
        subnetwork_manning: nt
        # Manning's roughness coefficient for main channel flow
        channel_manning: nr
        # topographic slope field name
        hillslope: hslp
        # drainage density field name [m^-1]
        drainage_density: gxr
        # mean tributary channel slope averaged through the unit field name
        subnetwork_slope:  tslp
        # bankfull width of local tributaries field name [m]
        subnetwork_width: twid
        # main channel length field name [m]
        channel_length: rlen
        # main channel slope field name
        channel_slope: rslp
        # bankfull width of main channel field name [m]
        channel_width: rwid
        # floodplain width linked to main channel field name [m]
        channel_floodplain_width: rwid0
        # bankfull depth of main channel field name [m]
        grid_channel_depth: rdep
        # land fraction field name
        land_fraction: frac
###
### Runoff (forcing input)
###
runoff:
    # flag to enable/disable reading runoff from file
    # if disabled, runoff variables should be provided by the model driver
    read_from_file: true
    # path to the runoff file; can be absolute or relative to the source code root
    path: ./input/runoff/Livneh_NLDAS_1980_1985.nc
    # longitude field name
    longitude: lon
    # latitude field name
    latitude: lat
    # time field name
    time: time
    # variables
    variables:
        # surface runoff [mm/s]
        surface_runoff: QOVER
        # subsurface runoff [mm/s]
        subsurface_runoff: QDRAI
        # wetland runoff [mm/s]
        wetland_runoff: ~

###
### Water Management (Demand and Reservoirs)
###
water_management:
    # flag to turn this feature on or off
    enabled: true
    # demand settings
    demand:
        # farmer Agent Based Model (ABM) calculation of demand
        farmer_abm:
            # flag to enable/disable using a farmer ABM to calculate water demand
            enabled: false
            # defines the agent's "memory decay rate" - higher mu values indicate higher decay (1 indicates that agent only remembers previous year)
            mu: 0.2
            # how many years to use the external baseline water demand files before starting ABM calculations
            warmup_period: 10
            land_water_constraints:
                # path to the land/water constraints by farm file; can be absolute or relative to the source code root
                path: ./input/demand/farmer_abm/land_water_constraints_by_farm.parquet
                # variable names
                variables:
                    # NLDAS identifier for the grid cell
                    nldas_id: nldas_id
                    # land constraints by farm field
                    land_constraints_by_farm: land_constraints_by_farm
                    # Surface water irrigation volume [acre-ft/year]
                    sw_irrigation_vol: sw_irrigation_vol
            land_water_constraints_live:
                # path to the live land/water constraints by farm file; can be absolute or relative to the source code root
                path: ./input/demand/farmer_abm/land_water_constraints_by_farm_live.parquet
            historic_storage_supply:
                # path to the historic storage/supply bias file; can be absolute or relative to the source code root
                path: ./input/demand/farmer_abm/historic_storage_supply_bias.parquet
                variables:
                    # field name for the NLDAS identifier for the grid cell
                    nldas_id: nldas_id
                    # field name for the original storage sum
                    storage_sum_original: storage_sum_original
                    # field name for the original supply
                    wrm_supply_original: wrm_supply_original
                    # field name for the previous supply
                    wrm_supply_prev: wrm_supply_prev
                    # field name for surface water available with bias correction
                    sw_avail_bias_corrected: sw_avail_bias_corrected
                    # field name for the demand factor
                    demand_factor: demand_factor
                    # field name for the original discharge
                    river_discharge_over_land_liquid_original: river_discharge_over_land_liquid_original
            crop_prices_by_nldas_id:
                # path to the crop prices file; can be absolute or relative to the source code root
                path: ./input/demand/farmer_abm/crop_prices_by_nldas_id.parquet
                variables:
                    # field name for the calculated area
                    calculated_area: calculated_area
                    # field name for the calculated water demand
                    calculated_water_demand: calculated_water_demand
                    # field name for the crop identifier
                    crop: crop
                    # field name for the net irrigation requirement
                    nir: nir
                    # field name for the corrected net irrigation requirement
                    nir_corrected: nir_corrected
                    # field name for the gammas
                    gammas: gammas
                    # field name for the net prices
                    net_prices: net_prices
                    # field name for the NLDAS identifier for the grid cell
                    nldas_id: nldas_id
            output:
                # path to the directory in which to write new demand files; can be absolute or relative to the source code root
                path: ./output/demand
          
        # flag to enable/disable reading demand from file
        # if disabled, demand should be provided by the model driver
        read_from_file: true
        # path to the demand file; can be absolute or relative to the source code root
        path: ./input/demand/RCP8.5_GCAM_water_demand_1980_1985.nc
        # longitude field name
        longitude: lon
        # latitude field name
        latitude: lat
        # time field name
        time: time
        # demand field name # TODO support the different demand types using the flags
        # todo: change to be consistent with other variable names: total_demand
        demand: totalDemand
        # TODO these modules aren't available yet
        # flag to enable or disable groundwater
        groundwater_enabled: false
        # flag to enable or disable return flow
        return_flow_enabled: false
        # flag to enable or disable the tracking of irrigation vs non irrigation demand
        total_demand_enabled: false
    # reservoir settings
    reservoirs:
        # use improved reservoir schedule module (ISTARF)
        enable_istarf: true
        # physical and use type parameters of the reservoirs, typically from GRanD
        parameters:
            # path to the reservoir parameter file; can be absolute or relative to the source code root
            path: ./input/reservoirs/reservoirs.nc
            # grid cell index field
            grid_cell_index: GRID_CELL_INDEX
            # variable field names
            variables:
                # reservoir id field name - typically the GRanD ID
                reservoir_id: GRAND_ID
                # reservoir grid cell index field name
                reservoir_grid_index: GRID_CELL_INDEX
                # height field name [m]
                reservoir_height: DAM_HGT_M
                # length field name [m]
                reservoir_length: DAM_LEN_M
                # surface area field name [km2]
                reservoir_surface_area: AREA_SKM
                # storage capacity field name [million m3]
                reservoir_storage_capacity: CAP_MCM
                # depth field name [m]
                reservoir_depth: DEPTH_M
                # use irrigation field name
                reservoir_use_irrigation: USE_IRRI
                # use electricity field name
                reservoir_use_electricity: USE_ELEC
                # use supply field name
                reservoir_use_supply: USE_SUPP
                # use flood control field name
                reservoir_use_flood_control: USE_FCON
                # use recreation field name
                reservoir_use_recreation: USE_RECR
                # use navigation field name
                reservoir_use_navigation: USE_NAVI
                # use fish protection field name
                reservoir_use_fish_protection: USE_FISH
                # ISTARF (improved reservoir schedule) parameters
                reservoir_grand_meanflow_cumecs: grand_meanflow_cumecs
                reservoir_observed_meanflow_cumecs: observed_meanflow_cumecs
                reservoir_upper_alpha: upper_alpha
                reservoir_upper_beta: upper_beta
                reservoir_upper_max: upper_max
                reservoir_upper_min: upper_min
                reservoir_upper_mu: upper_mu
                reservoir_lower_alpha: lower_alpha
                reservoir_lower_beta: lower_beta
                reservoir_lower_max: lower_max
                reservoir_lower_min: lower_min
                reservoir_lower_mu: lower_mu
                reservoir_release_alpha_one: release_alpha_one
                reservoir_release_alpha_two: release_alpha_two
                reservoir_release_beta_one: release_beta_one
                reservoir_release_beta_two: release_beta_two
                reservoir_release_c: release_c
                reservoir_release_max: release_max
                reservoir_release_min: release_min
                reservoir_release_p_one: release_p_one
                reservoir_release_p_two: release_p_two
                # field name for a value that allows setting the behavior of the reservoir release per reservoir;
                # currently, if this field holds a value of "generic" for a particular reservoir,
                # istarf is disabled for that reservoir, any other value in the field enables istarf
                reservoir_behavior: fit
        # database of grid cell indices that can extract from each reservoir
        dependencies:
            # path to the database dependency file; can be absolute or relative to the source code root
            path: ./input/reservoirs/dependency_database.parquet
            # variable field names
            variables:
                # flattened index of dependent grid cell
                dependent_cell_index: DEPENDENT_CELL_INDEX
                # ID of the reservoir
                dependent_reservoir_id: GRAND_ID
                # Reservoir cell index
                reservoir_cell_index: RESERVOIR_CELL_INDEX
        # database of monthly mean streamflow for each reservoir
        streamflow:
            # path to the flow file; can be absolute or relative to the source code root
            path: ./input/reservoirs/mean_monthly_reservoir_flow.parquet
            # variable field names
            variables:
                # ID of the reservoir
                streamflow_reservoir_id: GRAND_ID
                # month index
                streamflow_month_index: MONTH_INDEX
                # mean streamflow for month
                streamflow: MEAN_FLOW
        # database of monthly mean demand for each reservoir
        demand:
          # path to the demand file; can be absolute or relative to the source code root
          path: ./input/reservoirs/mean_monthly_reservoir_demand.parquet
          # variable field names
          variables:
            # ID of the reservoir
            demand_reservoir_id: GRAND_ID
            # month index
            demand_month_index: MONTH_INDEX
            # mean streamflow for month
            demand: MEAN_DEMAND

###
### Inundation
###
inundation:
    # flag to turn this feature on or off
    enabled: false

###
### Sediment
###
sediment:
    # flag to turn this feature on or off
    enabled: false

###
### Reservoir Stratification
###
reservoir_stratification:
    # flag to turn this feature on or off
    enabled: false

###
### Heat
###
heat:
    # flag to turn this feature on or off
    enabled: false
